server:
  port: 9100
  servlet:
    context-path: /redis_demo/

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.211.189.152:3306/cpzs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: wn123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # redis 配置
  redis:
    host: 129.211.189.152 # 地址
    port: 6379  # 端口，默认为6379
    password: wn123456  # 密码
    database: 3 # 采用数据库、默认0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 8 # 连接池的最大数据库连接数
        max-wait: -1m  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10s  # 连接超时时间

logging:
  level:
    com.wn: debug
    org.springframework: warn

mybatis-plus:
  type-aliases-package: com.wn.demo.model
  mapper-locations: com/wn/demo/mapper/*Mapper.xml
